name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: docker build -t contdeltechdemo .


  security_scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start Application
        run: |
          npm install
          npm start &  # Startet die App im Hintergrund
          sleep 10  # Warten, bis die App läuft

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          target: 'http://localhost:3000'
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
