name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: docker build -t contdeltechdemo .

  security_scan:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Enable Docker
          run: |
            sudo systemctl start docker
            docker info

        - name: Start Application
          run: |
            docker build -t contdeltechdemo .
            docker run -d --rm -p 3000:3000 --name myapp contdeltechdemo
            for i in {1..30}; do
              curl -s http://localhost:3000 > /dev/null && break
              sleep 2
            done

        - name: Run OWASP ZAP Scan
          uses: zaproxy/action-baseline@v0.6.0
          with:
            target: 'http://localhost:3000'
